# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-and-test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: "18.8.0"
      - node/install-packages
      - Setup tests and activate this comman
      - run:
          command: npm run test
      - run:
          name: "Speaksfer Blog App"
          command: "echo This is the UI of the Speaksfer Blog Application"
workflows:
  build-and-test:
    jobs:
      - build-and-test
